apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - todo-namespace.yaml
  - todo-db-secret.yaml
  - todo-db-pvc.yaml
  - todo-db-deployment.yaml
  - todo-db-service.yaml
  - todo-backend-deployment.yaml
  - todo-backend-service.yaml
  - todo-app-deployment.yaml
  - todo-app-service.yaml
  - ingress.yaml

images:
  - name: todo-app
    newName: us-central1-docker.pkg.dev/todo-app-458207/todo-app-repo/todo-app
    newTag: latest
  - name: todo-backend
    newName: us-central1-docker.pkg.dev/todo-app-458207/todo-backend-repo/todo-backend
    newTag: latest
