apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - todo-db-deployment.yaml
  - todo-db-service.yaml
  - todo-db-pvc.yaml
  - todo-backend-deployment.yaml
  - todo-backend-service.yaml
  - todo-app-deployment.yaml
  - todo-app-service.yaml
  - ingress.yaml

images:
  - name: todo-app
    newName: gcr.io/todo-app-458207/todo-app
    newTag: latest
