apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: todo-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: alketaz/todo-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: postgres://todouser:todopass@todo-db:5432/tododb
