name: Release TODO App

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: todo-cluster
  GKE_ZONE: us-central1-a
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      - name: Authenticate Docker to Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      # Build Frontend (todo-app)
      - name: Build Frontend Docker Image (todo-app)
        run: docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/todo-app-repo/todo-app:$BRANCH-$GITHUB_SHA ./todo-app

      # Build Backend (todo-backend)
      - name: Build Backend Docker Image (todo-backend)
        run: docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/todo-app-repo/todo-backend:$BRANCH-$GITHUB_SHA ./todo-backend

      # Push Frontend
      - name: Push Frontend Docker Image
        run: docker push us-central1-docker.pkg.dev/$PROJECT_ID/todo-app-repo/todo-app:$BRANCH-$GITHUB_SHA

      # Push Backend
      - name: Push Backend Docker Image
        run: docker push us-central1-docker.pkg.dev/$PROJECT_ID/todo-app-repo/todo-backend:$BRANCH-$GITHUB_SHA

      # Set up Kustomize
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      # Deploy to GKE
      - name: Deploy to GKE
        run: |
          kustomize edit set image todo-app=us-central1-docker.pkg.dev/$PROJECT_ID/todo-app-repo/todo-app:$BRANCH-$GITHUB_SHA
          kustomize edit set image todo-backend=us-central1-docker.pkg.dev/$PROJECT_ID/todo-app-repo/todo-backend:$BRANCH-$GITHUB_SHA
          
          kustomize build ./k8s | kubectl apply -f -
          
          kubectl rollout status deployment/todo-app -n todo-project
          kubectl rollout status deployment/todo-backend -n todo-project
          
          kubectl get services -n todo-project -o wide
