name: Release TODO App - Branch Based

on:
  push:
    branches:
      - '**'    # Listen to all branches

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: todo-cluster
  GKE_ZONE: us-central1
  BRANCH: ${{ github.ref_name }}
  REGION: us-central1
  FRONT_IMAGE: todo-app
  BACK_IMAGE: todo-backend
  FRONT_REPO: todo-app-repo
  BACK_REPO: todo-backend-repo
  NAMESPACE: ${{ github.ref_name == 'main' && 'todo-project' || format('todo-project-{0}', github.ref_name) }}

jobs:
  build-publish-deploy:
    name: Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      - name: Configure Docker to use Google Artifact Registry
        run: gcloud --quiet auth configure-docker ${REGION}-docker.pkg.dev

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name: Build Frontend Docker Image (todo-app)
        run: docker build -t ${REGION}-docker.pkg.dev/$PROJECT_ID/$FRONT_REPO/$FRONT_IMAGE:$BRANCH-$GITHUB_SHA ./todo-app

      - name: Build Backend Docker Image (todo-backend)
        run: docker build -t ${REGION}-docker.pkg.dev/$PROJECT_ID/$BACK_REPO/$BACK_IMAGE:$BRANCH-$GITHUB_SHA ./todo-backend

      - name: Push Frontend Docker Image
        run: docker push ${REGION}-docker.pkg.dev/$PROJECT_ID/$FRONT_REPO/$FRONT_IMAGE:$BRANCH-$GITHUB_SHA

      - name: Push Backend Docker Image
        run: docker push ${REGION}-docker.pkg.dev/$PROJECT_ID/$BACK_REPO/$BACK_IMAGE:$BRANCH-$GITHUB_SHA

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Deploy to GKE
        run: |
          cd k8s

          # Update images dynamically
          kustomize edit set image todo-app=${REGION}-docker.pkg.dev/$PROJECT_ID/$FRONT_REPO/$FRONT_IMAGE:$BRANCH-$GITHUB_SHA
          kustomize edit set image todo-backend=${REGION}-docker.pkg.dev/$PROJECT_ID/$BACK_REPO/$BACK_IMAGE:$BRANCH-$GITHUB_SHA

          # Create namespace if it doesn't exist
          kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -

          # Apply Kubernetes resources into the correct namespace
          kustomize build . | kubectl apply -n $NAMESPACE -f -

          echo "Waiting for frontend deployment rollout..."
          for i in {1..10}; do
            kubectl rollout status deployment/todo-app -n $NAMESPACE && break
            echo "Retrying frontend rollout in 5s..."
            sleep 5
          done

          echo "Waiting for backend deployment rollout..."
          for i in {1..10}; do
            kubectl rollout status deployment/todo-backend -n $NAMESPACE && break
            echo "Retrying backend rollout in 5s..."
            sleep 5
          done

          kubectl get pods -n $NAMESPACE
          kubectl get services -n $NAMESPACE
